# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: TravelPlanProject
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: krushit
    password: krushit
  jpa:
    show-sql: true
server:
  port: 4040

travelPlan:
  messages:
    save-success: Travel plan is registered with id value
    save-failure: Oops..!! Something went wrong
    find-by-id-failure: Travel Plan is found
    update-success: Travel Plan is updated
    update-failure: Travel Plan is not found for updation
    delete-success: Travel Plan is deleted
    delete-failure: Travel Plan is not found for deletion
    status-change-success: Travel Plan Status is changed
    status-change-failure: Travel Plan is not found for deletion